# Website settings
title: Dimpy
description: Dimpy's site of wonder!
keywords: dimpy,dimpyc,dimpychhabra,blog,github,gh-pages
baseurl:  
url: https://dimpy-chhabra.github.io/  
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

author:  # change following line to your infomation.
  name: Dimpy Chhabra  # Be used at blog posts' author.
  first_name: Dimpy  # Be used at index page about me section.
  last_name: Chhabra  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: dimpy-chhabra  
  linkedin_id: dimpy-chhabra 
  facebook_username: dimpychhabra20 
  twitter_username:  
  email: dimpychhabra@yahoo.co.uk 
  cv: https://drive.google.com/file/d/1G67XVR1GIMk-6wPAgzHyKjAoC5mspJtC/view?usp=sharing 
 # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: Hey, I am Dimpy Chhabra, a prefinal year student at Indira Gandhi Delhi Technical University for Women pursuing Bachelors of Technology in Information Technology. I love to code and develop real-time solutions to problems.When I am not coding, I enjoy reading, outdoor activities, public speaking, group discussions and most passionately following news on modern physics and cosmology. Other than exploring new sciences & technologies and working on projects, I try my part to promote women who code. I am a fellow mentor at ACM-IGDTU and am presently leading a mentorship program with over 65 students.

# comment
#disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  #name: dimpy

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
   id: UA-114858349-1

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: off  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

